version: 0.2

cache:
  paths:
    - "node_modules/**/*"
    - "/root/.cache/ms-playwright/**/*"

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - echo "Installing dependencies"

      - npm ci

      - |
        if [ ! -d "/root/.cache/ms-playwright" ]; then
          echo "Installing Playwright browsers first time"
          npx playwright install chromium
        else
          echo "Playwright browsers already cached"
        fi

  build:
    commands:
      - echo "Running Playwright tests"

      - npm test

  post_build:
    commands:
      - echo "Generating Playwright report"

      - npx playwright show-report --host 0.0.0.0 &
      - export TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
      - echo "Uploading report to S3"

      - aws s3 cp playwright-report s3://aws-demo-playwright-testapp-logs/reports/$TIMESTAMP/ --recursive
      - aws s3 cp test-results s3://aws-demo-playwright-testapp-logs/reports/$TIMESTAMP/test-results/ --recursive

      - echo "Deploying website"

      - chmod 600 scripts/id_rsa

      - mkdir -p ~/.ssh

      - cp scripts/id_rsa ~/.ssh/id_rsa

      - chmod 600 ~/.ssh/id_rsa

      - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "echo connected"

      - scp -i ~/.ssh/id_rsa -r index.html style.css ubuntu@$EC2_HOST:/tmp/

      - |
        ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST "
        sudo cp /tmp/index.html /var/www/html/index.html &&
        sudo cp /tmp/style.css /var/www/html/style.css
        "

artifacts:
  files:
    - "**/*"
